# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm start --allowGuess
    - run: npm start licenses.test.txt --allowGuess
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: 'licenses.test.txt' # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: 'licenses.test.txt'
        warn: true
